const assert=require("node:assert/strict")
const fs=require("node:fs")
const manifest=JSON.parse(fs.readFileSync("manifest.json","utf8"))
const changelog=fs.readFileSync("CHANGELOG.md","utf8")
const license=fs.readFileSync("LICENSE","utf8")
const notice=fs.readFileSync("NOTICE","utf8")
const release=fs.readFileSync(".github/workflows/release.yml","utf8")
assert.equal(manifest.id,"io.github.bolens.app-drawer")
assert.match(manifest.version,/^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/)
assert.match(changelog,new RegExp(`^## \\[${manifest.version.replace(/\./g,"\\.")}\\] - \\d{4}-\\d{2}-\\d{2}$`,"m"))
for(const holder of ["Amit Patel","David Heinemeier Hansson","bolens"]) assert.ok(license.includes(holder),`missing license holder: ${holder}`)
assert.ok(notice.includes("https://github.com/amitcpatel/omabar-drawer"))
assert.ok(release.includes('archive="omarchy-app-drawer-$version.tar.gz"'))
const preview=fs.readFileSync("preview.png"); assert.equal(preview.subarray(1,4).toString(),"PNG")
console.log("App Drawer release and license metadata passed")
