const assert = require("node:assert/strict")
const fs = require("node:fs")
const os = require("node:os")
const path = require("node:path")
const {spawnSync} = require("node:child_process")
const root = path.join(__dirname, "..")
const temp = fs.mkdtempSync(path.join(os.tmpdir(), "drawer-scripts-"))
try {
  const config = path.join(temp, "shell.json")
  fs.writeFileSync(config, JSON.stringify({version:1,bar:{id:"legacy",layout:{right:["one",{id:"io.github.amitcpatel.omabar-drawer"}]}},plugins:[]})+"\n")
  let result = spawnSync(path.join(root,"scripts/migrate-to-stock-bar"), [config], {encoding:"utf8"})
  assert.equal(result.status, 0, result.stderr)
  const migrated = JSON.parse(fs.readFileSync(config,"utf8"))
  assert.equal(migrated.bar.id, "omarchy.bar")
  assert.deepEqual(migrated.bar.layout.right, ["one","io.github.bolens.app-drawer"])
  assert.equal(migrated.bar.drawerExpanded, true)
  assert.ok(fs.existsSync(config+".pre-app-drawer-v2"))

  const install = path.join(temp,"plugin"); fs.mkdirSync(install)
  result = spawnSync(path.join(root,"scripts/deploy-shell-runtime"), [install], {encoding:"utf8"})
  assert.equal(result.status, 0, result.stderr)
  for (const file of fs.readdirSync(root).filter(name => /\.(qml|js)$/.test(name)).concat(["manifest.json"]))
    assert.deepEqual(fs.readFileSync(path.join(install,file)), fs.readFileSync(path.join(root,file)), `deploy mismatch: ${file}`)

  const invalid = path.join(temp,"invalid.json"); fs.writeFileSync(invalid,"not json\n")
  result = spawnSync(path.join(root,"scripts/migrate-to-stock-bar"), [invalid], {encoding:"utf8"})
  assert.notEqual(result.status, 0)
  assert.equal(fs.readFileSync(invalid,"utf8"), "not json\n", "failed migration modified its input")
} finally { fs.rmSync(temp,{recursive:true,force:true}) }
console.log("App Drawer migration and deployment scripts passed")
