const assert=require("node:assert/strict"),fs=require("node:fs")
assert.ok(fs.statSync("scripts/build-site.sh").mode&0o100,"site builder must remain executable")
const html=fs.readFileSync("docs/index.html","utf8"),css=fs.readFileSync("docs/styles.css","utf8")
for(const id of ["main","features","appearance","technical","install"]) assert.ok(html.includes(`id="${id}"`),`missing section ${id}`)
for(const asset of ["styles.css","site.js","favicon.svg","preview.png"]) assert.ok(html.includes(asset),`missing asset ${asset}`)
for(const term of ["per-monitor","No extra shell","Guarded IPC","MIT licensed"]) assert.match(html,new RegExp(term,"i"))
assert.match(html,/\{\{VERSION\}\}/); assert.match(html,/class="skip"/); assert.match(css,/prefers-reduced-motion/)
assert.match(css,/#ae73ff/i); assert.match(css,/#ffbe62/i)
const image=fs.readFileSync("preview.png"); assert.equal(image.subarray(1,4).toString(),"PNG")
assert.equal(image.readUInt32BE(16),1200,"preview must retain its comparison width")
assert.equal(image.readUInt32BE(20),504,"preview must retain its two-state comparison height")
assert.equal((html.match(/<h1/g)||[]).length,1); assert.equal((html.match(/data-copy/g)||[]).length,1)
console.log("App Drawer Pages structure passed")
