const assert=require("node:assert/strict"),fs=require("node:fs")
assert.ok(fs.statSync("scripts/build-site.sh").mode&0o100,"site builder must remain executable")
const html=fs.readFileSync("docs/index.html","utf8"),css=fs.readFileSync("docs/styles.css","utf8")
for(const id of ["main","features","appearance","technical","install"]) assert.ok(html.includes(`id="${id}"`),`missing section ${id}`)
for(const asset of ["styles.css","motion-gallery.css","site.js","favicon.svg"]) assert.ok(html.includes(asset),`missing asset ${asset}`)
for(const style of ["taskbar","cascade","soft-cascade","uniform","instant"])
  {
    assert.ok(html.includes(`motion/${style}.webp`),`missing ${style} motion preview`)
    const motion=fs.readFileSync(`docs/motion/${style}.webp`)
    assert.equal(motion.subarray(0,4).toString(),"RIFF")
    assert.equal(motion.subarray(8,12).toString(),"WEBP")
    assert.ok(motion.length>4096,`${style} motion preview is unexpectedly small`)
  }
for(const term of ["per-monitor","No extra shell","Guarded IPC","MIT licensed"]) assert.match(html,new RegExp(term,"i"))
assert.match(html,/\{\{VERSION\}\}/); assert.match(html,/class="skip"/); assert.match(css,/prefers-reduced-motion/)
assert.match(css,/#ae73ff/i); assert.match(css,/#ffbe62/i)
const image=fs.readFileSync("preview.png"); assert.equal(image.subarray(1,4).toString(),"PNG")
assert.equal(image.readUInt32BE(16),1200,"preview must retain its comparison width")
assert.equal(image.readUInt32BE(20),504,"preview must retain its two-state comparison height")
for(const state of ["collapsed","expanded"]){
  const screenshot=fs.readFileSync(`screenshots/${state}.png`)
  assert.equal(screenshot.subarray(1,4).toString(),"PNG")
  assert.equal(screenshot.readUInt32BE(16),1200,`${state} screenshot must match comparison width`)
  assert.equal(screenshot.readUInt32BE(20),180,`${state} screenshot must match comparison height`)
}
const galleryCss=fs.readFileSync("docs/motion-gallery.css","utf8")
assert.match(galleryCss,/\.motion-gallery\s*\{[^}]*display:\s*grid/)
assert.match(galleryCss,/aspect-ratio:\s*20\s*\/\s*3/)
assert.equal((html.match(/<h1/g)||[]).length,1); assert.equal((html.match(/data-copy/g)||[]).length,1)
console.log("App Drawer Pages structure passed")
