const assert=require("node:assert/strict"),fs=require("node:fs")
const {dimensions}=require("./png")
assert.ok(fs.statSync("scripts/build-site.sh").mode&0o100,"site builder must remain executable")
const html=fs.readFileSync("docs/index.html","utf8"),css=fs.readFileSync("docs/styles.css","utf8")
const themeCss=fs.readFileSync("docs/theme.css","utf8"),themeJs=fs.readFileSync("docs/theme.js","utf8")
const notFound=fs.readFileSync("docs/404.html","utf8")
const previewBuilder=fs.readFileSync("scripts/build-motion-previews","utf8")
for(const id of ["main","features","appearance","technical","install"]) assert.ok(html.includes(`id="${id}"`),`missing section ${id}`)
for(const asset of ["styles.css","theme.css","theme.js","motion-gallery.css","site.js","favicon.svg","apple-touch-icon.png","site.webmanifest","social-card.png"]) assert.ok(html.includes(asset),`missing asset ${asset}`)
for(const contract of ["canonical","og:type","og:url","og:site_name","og:image:width","twitter:card","twitter:title","twitter:description","twitter:image","twitter:image:alt"]) assert.ok(html.includes(contract),`missing metadata ${contract}`)
assert.deepEqual(dimensions("docs/social-card.png","social card"),[1200,630])
for(const theme of ["github-light","catppuccin-latte","solarized-light"]) assert.ok(html.includes(`value="${theme}"`),`missing ${theme} option`)
assert.match(html,/prefers-color-scheme: light/);assert.match(html,/\? "github-light" : root\.dataset\.defaultTheme/)
assert.match(html,/localStorage\.getItem\(root\.dataset\.themeStorage\)/)
assert.match(themeCss,/\[data-theme="github-light"\]\s*\{\s*color-scheme:light/);assert.match(themeJs,/if \(themeColor\)/);assert.match(themeJs,/if \(root\.dataset\.themeStorage\)/)
assert.match(themeCss,/\.proof strong,[^}]*\.install \.eyebrow\)\{color:var\(--ink\)\}/)
assert.match(notFound,/prefers-color-scheme: light/);assert.match(notFound,/URLSearchParams/);assert.match(notFound,/root\.dataset\.themeStorage/)
for(const style of ["taskbar","cascade","soft-cascade","uniform","instant"])
  {
    assert.ok(html.includes(`motion/${style}.webp`),`missing ${style} motion preview`)
    const motion=fs.readFileSync(`docs/motion/${style}.webp`)
    assert.equal(motion.subarray(0,4).toString(),"RIFF")
    assert.equal(motion.subarray(8,12).toString(),"WEBP")
    assert.ok(motion.length>4096,`${style} motion preview is unexpectedly small`)
  }
for(const term of ["per-monitor","No extra shell","Guarded IPC","MIT licensed"]) assert.match(html,new RegExp(term,"i"))
assert.match(html,/\{\{VERSION\}\}/); assert.match(html,/class="skip"/); assert.match(css,/prefers-reduced-motion/)
assert.match(css,/#ae73ff/i); assert.match(css,/#ffbe62/i)
assert.deepEqual(dimensions("preview.png","preview"),[1200,504],"preview must retain its two-state comparison frame")
for(const state of ["collapsed","expanded"]){
  assert.deepEqual(dimensions(`screenshots/${state}.png`,`${state} screenshot`),[1200,180],
    `${state} screenshot must match the comparison frame`)
}
const galleryCss=fs.readFileSync("docs/motion-gallery.css","utf8")
assert.match(galleryCss,/\.motion-gallery\s*\{[^}]*display:\s*grid/)
assert.match(galleryCss,/aspect-ratio:\s*20\s*\/\s*3/)
assert.match(html,/<section class="motion-gallery"[^>]*aria-label=/,
  "motion previews must use a labelled landmark")
const progress=previewBuilder.match(/^progress=\(([^)]*)\)$/m)
const delay=previewBuilder.match(/^\s*magick -delay (\d+) -loop 0 "\$\{frames\[@\]\}"/m)
assert.ok(progress&&delay,"motion preview timing must remain inspectable")
assert.equal(progress[1].trim().split(/\s+/).length*Number(delay[1]),120,
  "animated previews must retain the original 120-tick duration")
assert.equal((html.match(/<h1/g)||[]).length,1); assert.equal((html.match(/data-copy/g)||[]).length,1)
console.log("App Drawer Pages structure passed")
